#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : msrest
Version  : 0.6.19
Release  : 31
URL      : https://files.pythonhosted.org/packages/6f/ad/fc4dc6c53ec8db010e9acbb1cb6c2626bed9a6646fc5a3383d171affb375/msrest-0.6.19.tar.gz
Source0  : https://files.pythonhosted.org/packages/6f/ad/fc4dc6c53ec8db010e9acbb1cb6c2626bed9a6646fc5a3383d171affb375/msrest-0.6.19.tar.gz
Summary  : AutoRest swagger generator Python client runtime.
Group    : Development/Tools
License  : MIT
Requires: msrest-python = %{version}-%{release}
Requires: msrest-python3 = %{version}-%{release}
Requires: aiohttp
Requires: certifi
Requires: isodate
Requires: requests-oauthlib
BuildRequires : aiohttp
BuildRequires : buildreq-distutils3
BuildRequires : certifi
BuildRequires : isodate
BuildRequires : requests-oauthlib

%description
===============================

%package python
Summary: python components for the msrest package.
Group: Default
Requires: msrest-python3 = %{version}-%{release}

%description python
python components for the msrest package.


%package python3
Summary: python3 components for the msrest package.
Group: Default
Requires: python3-core
Provides: pypi(msrest)
Requires: pypi(certifi)
Requires: pypi(isodate)
Requires: pypi(requests)
Requires: pypi(requests_oauthlib)

%description python3
python3 components for the msrest package.


%prep
%setup -q -n msrest-0.6.19
cd %{_builddir}/msrest-0.6.19

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1599602223
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
