#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : msrest
Version  : 0.6.6
Release  : 7
URL      : https://files.pythonhosted.org/packages/0b/ec/437da5296f540830eb7fe0d0d06e4f3f4d97b82ef369b637dec76bf20f3e/msrest-0.6.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/0b/ec/437da5296f540830eb7fe0d0d06e4f3f4d97b82ef369b637dec76bf20f3e/msrest-0.6.6.tar.gz
Summary  : AutoRest swagger generator Python client runtime.
Group    : Development/Tools
License  : MIT
Requires: msrest-python = %{version}-%{release}
Requires: msrest-python3 = %{version}-%{release}
Requires: aiohttp
Requires: certifi
Requires: enum34
Requires: isodate
Requires: requests-oauthlib
Requires: typing
BuildRequires : buildreq-distutils3
BuildRequires : certifi
BuildRequires : isodate
BuildRequires : requests-oauthlib

%description
AutoRest: Python Client Runtime
===============================
.. image:: https://travis-ci.org/Azure/msrest-for-python.svg?branch=master
:target: https://travis-ci.org/Azure/msrest-for-python

%package python
Summary: python components for the msrest package.
Group: Default
Requires: msrest-python3 = %{version}-%{release}

%description python
python components for the msrest package.


%package python3
Summary: python3 components for the msrest package.
Group: Default
Requires: python3-core

%description python3
python3 components for the msrest package.


%prep
%setup -q -n msrest-0.6.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1555171533
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
